services:
  postgres:
    image: postgres:18
    container_name: inventoryTracker-db
    environment:
      POSTGRES_DB: InventoryTracker
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: inventoryTracker-app
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"