CREATE TABLE IF NOT EXISTS inventory_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    supplier_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    
    quantity INT NOT NULL,
    note VARCHAR(255),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    transaction_type VARCHAR(50) NOT NULL,
    
    FOREIGN KEY (user_id) REFERENCES app_user(id),
    FOREIGN KEY (product_id) REFERENCES product(id),
    FOREIGN KEY (supplier_id) REFERENCES supplier(id),
    FOREIGN KEY (location_id) REFERENCES location(id)
);